//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TermProject.BlackboardSvcPxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BlackBoardServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class BlackBoardService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifyLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback addStudentOperationCompleted;
        
        private System.Threading.SendOrPostCallback addCourseBuilderOperationCompleted;
        
        private System.Threading.SendOrPostCallback addBBAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback addCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnrollCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTermOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCourseByTermOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCourseByCBIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback populateStudentsInCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback addStudentsToCourseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BlackBoardService() {
            this.Url = global::TermProject.Properties.Settings.Default.TermProject_BlackboardSvcPxy_BlackBoardService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event verifyLoginCompletedEventHandler verifyLoginCompleted;
        
        /// <remarks/>
        public event addStudentCompletedEventHandler addStudentCompleted;
        
        /// <remarks/>
        public event addCourseBuilderCompletedEventHandler addCourseBuilderCompleted;
        
        /// <remarks/>
        public event addBBAdminCompletedEventHandler addBBAdminCompleted;
        
        /// <remarks/>
        public event addCourseCompletedEventHandler addCourseCompleted;
        
        /// <remarks/>
        public event DeleteCourseCompletedEventHandler DeleteCourseCompleted;
        
        /// <remarks/>
        public event EnrollCourseCompletedEventHandler EnrollCourseCompleted;
        
        /// <remarks/>
        public event EmailCourseCompletedEventHandler EmailCourseCompleted;
        
        /// <remarks/>
        public event GetDepartmentCompletedEventHandler GetDepartmentCompleted;
        
        /// <remarks/>
        public event GetTermCompletedEventHandler GetTermCompleted;
        
        /// <remarks/>
        public event GetUserTypeCompletedEventHandler GetUserTypeCompleted;
        
        /// <remarks/>
        public event GetCourseByTermCompletedEventHandler GetCourseByTermCompleted;
        
        /// <remarks/>
        public event GetCourseByCBIDCompletedEventHandler GetCourseByCBIDCompleted;
        
        /// <remarks/>
        public event UpdateCourseCompletedEventHandler UpdateCourseCompleted;
        
        /// <remarks/>
        public event populateStudentsInCourseCompletedEventHandler populateStudentsInCourseCompleted;
        
        /// <remarks/>
        public event addStudentsToCourseCompletedEventHandler addStudentsToCourseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verifyLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] verifyLogin(string username, string password) {
            object[] results = this.Invoke("verifyLogin", new object[] {
                        username,
                        password});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void verifyLoginAsync(string username, string password) {
            this.verifyLoginAsync(username, password, null);
        }
        
        /// <remarks/>
        public void verifyLoginAsync(string username, string password, object userState) {
            if ((this.verifyLoginOperationCompleted == null)) {
                this.verifyLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifyLoginOperationCompleted);
            }
            this.InvokeAsync("verifyLogin", new object[] {
                        username,
                        password}, this.verifyLoginOperationCompleted, userState);
        }
        
        private void OnverifyLoginOperationCompleted(object arg) {
            if ((this.verifyLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifyLoginCompleted(this, new verifyLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addStudent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addStudent(Student student, string key) {
            object[] results = this.Invoke("addStudent", new object[] {
                        student,
                        key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addStudentAsync(Student student, string key) {
            this.addStudentAsync(student, key, null);
        }
        
        /// <remarks/>
        public void addStudentAsync(Student student, string key, object userState) {
            if ((this.addStudentOperationCompleted == null)) {
                this.addStudentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddStudentOperationCompleted);
            }
            this.InvokeAsync("addStudent", new object[] {
                        student,
                        key}, this.addStudentOperationCompleted, userState);
        }
        
        private void OnaddStudentOperationCompleted(object arg) {
            if ((this.addStudentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addStudentCompleted(this, new addStudentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addCourseBuilder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addCourseBuilder(CourseBuilder cb, string key) {
            object[] results = this.Invoke("addCourseBuilder", new object[] {
                        cb,
                        key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addCourseBuilderAsync(CourseBuilder cb, string key) {
            this.addCourseBuilderAsync(cb, key, null);
        }
        
        /// <remarks/>
        public void addCourseBuilderAsync(CourseBuilder cb, string key, object userState) {
            if ((this.addCourseBuilderOperationCompleted == null)) {
                this.addCourseBuilderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddCourseBuilderOperationCompleted);
            }
            this.InvokeAsync("addCourseBuilder", new object[] {
                        cb,
                        key}, this.addCourseBuilderOperationCompleted, userState);
        }
        
        private void OnaddCourseBuilderOperationCompleted(object arg) {
            if ((this.addCourseBuilderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addCourseBuilderCompleted(this, new addCourseBuilderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addBBAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addBBAdmin(BBAdmin admin, string key) {
            object[] results = this.Invoke("addBBAdmin", new object[] {
                        admin,
                        key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addBBAdminAsync(BBAdmin admin, string key) {
            this.addBBAdminAsync(admin, key, null);
        }
        
        /// <remarks/>
        public void addBBAdminAsync(BBAdmin admin, string key, object userState) {
            if ((this.addBBAdminOperationCompleted == null)) {
                this.addBBAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddBBAdminOperationCompleted);
            }
            this.InvokeAsync("addBBAdmin", new object[] {
                        admin,
                        key}, this.addBBAdminOperationCompleted, userState);
        }
        
        private void OnaddBBAdminOperationCompleted(object arg) {
            if ((this.addBBAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addBBAdminCompleted(this, new addBBAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addCourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addCourse(Course course, string key) {
            object[] results = this.Invoke("addCourse", new object[] {
                        course,
                        key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addCourseAsync(Course course, string key) {
            this.addCourseAsync(course, key, null);
        }
        
        /// <remarks/>
        public void addCourseAsync(Course course, string key, object userState) {
            if ((this.addCourseOperationCompleted == null)) {
                this.addCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddCourseOperationCompleted);
            }
            this.InvokeAsync("addCourse", new object[] {
                        course,
                        key}, this.addCourseOperationCompleted, userState);
        }
        
        private void OnaddCourseOperationCompleted(object arg) {
            if ((this.addCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addCourseCompleted(this, new addCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteCourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteCourse(string course, string key) {
            object[] results = this.Invoke("DeleteCourse", new object[] {
                        course,
                        key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteCourseAsync(string course, string key) {
            this.DeleteCourseAsync(course, key, null);
        }
        
        /// <remarks/>
        public void DeleteCourseAsync(string course, string key, object userState) {
            if ((this.DeleteCourseOperationCompleted == null)) {
                this.DeleteCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCourseOperationCompleted);
            }
            this.InvokeAsync("DeleteCourse", new object[] {
                        course,
                        key}, this.DeleteCourseOperationCompleted, userState);
        }
        
        private void OnDeleteCourseOperationCompleted(object arg) {
            if ((this.DeleteCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCourseCompleted(this, new DeleteCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnrollCourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnrollCourse(string key) {
            this.Invoke("EnrollCourse", new object[] {
                        key});
        }
        
        /// <remarks/>
        public void EnrollCourseAsync(string key) {
            this.EnrollCourseAsync(key, null);
        }
        
        /// <remarks/>
        public void EnrollCourseAsync(string key, object userState) {
            if ((this.EnrollCourseOperationCompleted == null)) {
                this.EnrollCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnrollCourseOperationCompleted);
            }
            this.InvokeAsync("EnrollCourse", new object[] {
                        key}, this.EnrollCourseOperationCompleted, userState);
        }
        
        private void OnEnrollCourseOperationCompleted(object arg) {
            if ((this.EnrollCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnrollCourseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailCourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EmailCourse(string key) {
            this.Invoke("EmailCourse", new object[] {
                        key});
        }
        
        /// <remarks/>
        public void EmailCourseAsync(string key) {
            this.EmailCourseAsync(key, null);
        }
        
        /// <remarks/>
        public void EmailCourseAsync(string key, object userState) {
            if ((this.EmailCourseOperationCompleted == null)) {
                this.EmailCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailCourseOperationCompleted);
            }
            this.InvokeAsync("EmailCourse", new object[] {
                        key}, this.EmailCourseOperationCompleted, userState);
        }
        
        private void OnEmailCourseOperationCompleted(object arg) {
            if ((this.EmailCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailCourseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDepartment(string key) {
            object[] results = this.Invoke("GetDepartment", new object[] {
                        key});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentAsync(string key) {
            this.GetDepartmentAsync(key, null);
        }
        
        /// <remarks/>
        public void GetDepartmentAsync(string key, object userState) {
            if ((this.GetDepartmentOperationCompleted == null)) {
                this.GetDepartmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentOperationCompleted);
            }
            this.InvokeAsync("GetDepartment", new object[] {
                        key}, this.GetDepartmentOperationCompleted, userState);
        }
        
        private void OnGetDepartmentOperationCompleted(object arg) {
            if ((this.GetDepartmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentCompleted(this, new GetDepartmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTerm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTerm(string key) {
            object[] results = this.Invoke("GetTerm", new object[] {
                        key});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetTermAsync(string key) {
            this.GetTermAsync(key, null);
        }
        
        /// <remarks/>
        public void GetTermAsync(string key, object userState) {
            if ((this.GetTermOperationCompleted == null)) {
                this.GetTermOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTermOperationCompleted);
            }
            this.InvokeAsync("GetTerm", new object[] {
                        key}, this.GetTermOperationCompleted, userState);
        }
        
        private void OnGetTermOperationCompleted(object arg) {
            if ((this.GetTermCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTermCompleted(this, new GetTermCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUserType(string key) {
            object[] results = this.Invoke("GetUserType", new object[] {
                        key});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserTypeAsync(string key) {
            this.GetUserTypeAsync(key, null);
        }
        
        /// <remarks/>
        public void GetUserTypeAsync(string key, object userState) {
            if ((this.GetUserTypeOperationCompleted == null)) {
                this.GetUserTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserTypeOperationCompleted);
            }
            this.InvokeAsync("GetUserType", new object[] {
                        key}, this.GetUserTypeOperationCompleted, userState);
        }
        
        private void OnGetUserTypeOperationCompleted(object arg) {
            if ((this.GetUserTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserTypeCompleted(this, new GetUserTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCourseByTerm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCourseByTerm(string fk_termid, string key) {
            object[] results = this.Invoke("GetCourseByTerm", new object[] {
                        fk_termid,
                        key});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetCourseByTermAsync(string fk_termid, string key) {
            this.GetCourseByTermAsync(fk_termid, key, null);
        }
        
        /// <remarks/>
        public void GetCourseByTermAsync(string fk_termid, string key, object userState) {
            if ((this.GetCourseByTermOperationCompleted == null)) {
                this.GetCourseByTermOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCourseByTermOperationCompleted);
            }
            this.InvokeAsync("GetCourseByTerm", new object[] {
                        fk_termid,
                        key}, this.GetCourseByTermOperationCompleted, userState);
        }
        
        private void OnGetCourseByTermOperationCompleted(object arg) {
            if ((this.GetCourseByTermCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCourseByTermCompleted(this, new GetCourseByTermCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCourseByCBID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCourseByCBID(int fk_CBID, string key) {
            object[] results = this.Invoke("GetCourseByCBID", new object[] {
                        fk_CBID,
                        key});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetCourseByCBIDAsync(int fk_CBID, string key) {
            this.GetCourseByCBIDAsync(fk_CBID, key, null);
        }
        
        /// <remarks/>
        public void GetCourseByCBIDAsync(int fk_CBID, string key, object userState) {
            if ((this.GetCourseByCBIDOperationCompleted == null)) {
                this.GetCourseByCBIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCourseByCBIDOperationCompleted);
            }
            this.InvokeAsync("GetCourseByCBID", new object[] {
                        fk_CBID,
                        key}, this.GetCourseByCBIDOperationCompleted, userState);
        }
        
        private void OnGetCourseByCBIDOperationCompleted(object arg) {
            if ((this.GetCourseByCBIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCourseByCBIDCompleted(this, new GetCourseByCBIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateCourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateCourse(Course course, string key) {
            object[] results = this.Invoke("UpdateCourse", new object[] {
                        course,
                        key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCourseAsync(Course course, string key) {
            this.UpdateCourseAsync(course, key, null);
        }
        
        /// <remarks/>
        public void UpdateCourseAsync(Course course, string key, object userState) {
            if ((this.UpdateCourseOperationCompleted == null)) {
                this.UpdateCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCourseOperationCompleted);
            }
            this.InvokeAsync("UpdateCourse", new object[] {
                        course,
                        key}, this.UpdateCourseOperationCompleted, userState);
        }
        
        private void OnUpdateCourseOperationCompleted(object arg) {
            if ((this.UpdateCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCourseCompleted(this, new UpdateCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/populateStudentsInCourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet populateStudentsInCourse(string key, string courseID) {
            object[] results = this.Invoke("populateStudentsInCourse", new object[] {
                        key,
                        courseID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void populateStudentsInCourseAsync(string key, string courseID) {
            this.populateStudentsInCourseAsync(key, courseID, null);
        }
        
        /// <remarks/>
        public void populateStudentsInCourseAsync(string key, string courseID, object userState) {
            if ((this.populateStudentsInCourseOperationCompleted == null)) {
                this.populateStudentsInCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpopulateStudentsInCourseOperationCompleted);
            }
            this.InvokeAsync("populateStudentsInCourse", new object[] {
                        key,
                        courseID}, this.populateStudentsInCourseOperationCompleted, userState);
        }
        
        private void OnpopulateStudentsInCourseOperationCompleted(object arg) {
            if ((this.populateStudentsInCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.populateStudentsInCourseCompleted(this, new populateStudentsInCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addStudentsToCourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addStudentsToCourse(object[] arrStudents, string courseID) {
            this.Invoke("addStudentsToCourse", new object[] {
                        arrStudents,
                        courseID});
        }
        
        /// <remarks/>
        public void addStudentsToCourseAsync(object[] arrStudents, string courseID) {
            this.addStudentsToCourseAsync(arrStudents, courseID, null);
        }
        
        /// <remarks/>
        public void addStudentsToCourseAsync(object[] arrStudents, string courseID, object userState) {
            if ((this.addStudentsToCourseOperationCompleted == null)) {
                this.addStudentsToCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddStudentsToCourseOperationCompleted);
            }
            this.InvokeAsync("addStudentsToCourse", new object[] {
                        arrStudents,
                        courseID}, this.addStudentsToCourseOperationCompleted, userState);
        }
        
        private void OnaddStudentsToCourseOperationCompleted(object arg) {
            if ((this.addStudentsToCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addStudentsToCourseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Student {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string majorField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Course {
        
        private string courseIDField;
        
        private string nameField;
        
        private string fK_TermIDField;
        
        private int fK_CBIDField;
        
        private string courseCodeField;
        
        /// <remarks/>
        public string CourseID {
            get {
                return this.courseIDField;
            }
            set {
                this.courseIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string FK_TermID {
            get {
                return this.fK_TermIDField;
            }
            set {
                this.fK_TermIDField = value;
            }
        }
        
        /// <remarks/>
        public int FK_CBID {
            get {
                return this.fK_CBIDField;
            }
            set {
                this.fK_CBIDField = value;
            }
        }
        
        /// <remarks/>
        public string CourseCode {
            get {
                return this.courseCodeField;
            }
            set {
                this.courseCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BBAdmin {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CourseBuilder {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string usernameField;
        
        private string passwordField;
        
        private int fK_DeptIDField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int FK_DeptID {
            get {
                return this.fK_DeptIDField;
            }
            set {
                this.fK_DeptIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void verifyLoginCompletedEventHandler(object sender, verifyLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifyLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifyLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void addStudentCompletedEventHandler(object sender, addStudentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addStudentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addStudentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void addCourseBuilderCompletedEventHandler(object sender, addCourseBuilderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addCourseBuilderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addCourseBuilderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void addBBAdminCompletedEventHandler(object sender, addBBAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addBBAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addBBAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void addCourseCompletedEventHandler(object sender, addCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeleteCourseCompletedEventHandler(object sender, DeleteCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void EnrollCourseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void EmailCourseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetDepartmentCompletedEventHandler(object sender, GetDepartmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetTermCompletedEventHandler(object sender, GetTermCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTermCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTermCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetUserTypeCompletedEventHandler(object sender, GetUserTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCourseByTermCompletedEventHandler(object sender, GetCourseByTermCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCourseByTermCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCourseByTermCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCourseByCBIDCompletedEventHandler(object sender, GetCourseByCBIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCourseByCBIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCourseByCBIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UpdateCourseCompletedEventHandler(object sender, UpdateCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void populateStudentsInCourseCompletedEventHandler(object sender, populateStudentsInCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class populateStudentsInCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal populateStudentsInCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void addStudentsToCourseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591